events {}

http {
    server {
        listen 80;
        server_name ${DOMAIN};

        server_tokens off;
        proxy_no_cache 1;
        proxy_cache_bypass 1;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        client_max_body_size 100M;

        location = /favicon.ico {
            proxy_pass http://aes_tc_app:8000/favicon.ico;
            access_log off;
        }

        location / {
            proxy_pass http://aes_tc_app:8000;
            proxy_set_header Host $host;
            proxy_read_timeout 300s;
        }
    }
}